#!/usr/bin/python3
# ==============================================================#
# File      :   dns
# Desc      :   setup vagrant dns config
# Ctime     :   2021-04-20
# Mtime     :   2023-07-29
# Path      :   vagrant/dns
# Author    :   Ruohang Feng (rh@vonng.com)
# License   :   AGPLv3
# ==============================================================#
# this script will generate vagrant nodes DNS records
# and write to /etc/hosts of current machine
# sudo privilege is required for writing /etc/hosts
# DNS records without DNS_MARKER (suffix '# pigsty dns') will be kept

import os, sys

DNS_MARKER = '# pigsty dns'
STATIC_DNS = 'meta h.pigsty a.pigsty p.pigsty g.pigsty api.pigsty cli.pigsty sss.pigsty adm.pigsty lab.pigsty wiki.pigsty git.pigsty'

from vagrant import parse_vagrant_spec

def get_hosts_file_path():
    if sys.platform in ('linux', 'darwin'):
        return '/etc/hosts'
    elif sys.platform == 'win32':
        return 'C:/Windows/System32/drivers/etc/hosts'
    else:
        raise RuntimeError(f"{sys.platform} is not supported!")
    
def build_dns_records(specs):
    etc_hosts = []
    with open(get_hosts_file_path(), mode='r') as f:
        for line in f.readlines():
            if line.strip() == '':
                continue
            if DNS_MARKER not in line:
                etc_hosts.append(line)

    if not specs or len(specs) > 0:
        etc_hosts.append('\n\n' + DNS_MARKER + '\n')
        etc_hosts.append('%-16s %s %s\n' % (specs[0][0], STATIC_DNS, DNS_MARKER))
        for ip, name in specs:
            etc_hosts.append('%-16s %s %s\n' % (ip, name, DNS_MARKER))
    return etc_hosts


def write_etc_hosts(records):
    # check if I have write permission to /etc/hosts
    host_file = get_hosts_file_path()
    if not os.access(host_file, os.W_OK):
        print(f"you don't have write permission to {host_file}, try sudo")
        if sys.platform == 'win32':
            print("if sudo is not available, try instal gsudo (winget install gerardog.gsudo).")
        sys.exit(1)
    with open(host_file, mode='w') as f:
        f.write(''.join(records))
    print(f"write {host_file} complete!")


def main():
    # check vagrantfile exists
    vagrant_dir = os.path.dirname(os.path.realpath(__file__))
    os.chdir(vagrant_dir)
    vagrant_file = os.path.join(vagrant_dir, 'Vagrantfile')
    if not os.path.exists(vagrant_file):
        print("Vagrantfile not found in %s" % vagrant_file)
        sys.exit(1)

    # parse vagrantfile and generate ssh config
    mapping, specs = parse_vagrant_spec(vagrant_file)
    print("\n============= Vagrant nodes:\n")
    for ip, name in specs:
        print("%-16s %s" % (ip, name))
    print("\n\n")

    # build /etc/hosts records
    etc_hosts = build_dns_records(specs)
    print("\n============= DNS RECORDS @ /etc/hosts \n")
    print(''.join(etc_hosts))
    print('\n\n')

    write_etc_hosts(etc_hosts)


# main
if __name__ == '__main__':
    main()
